
import AuthProvider from '@/context/Authprovider'
import '../globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import AdminNavbar from'@/components/admin/AdminNavBar'
import { Toaster } from '@/components/ui/toaster'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex">
        <AuthProvider>

        <div className="flex h-full w-full">
            <div className="bg-green-500 w-[240px] ">
              <AdminNavbar />
            </div>

            <div className="flex-1  h-full overflow-auto">
            {children}
            <Toaster></Toaster>
            </div>
          </div>
        
        </AuthProvider>
        </body>
    </html>
  )
}
