import { icons } from "lucide-react"
import { Inter } from "next/font/google";
import "../../app/globals.css"
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: 'Drive2Dreams',
  description: 'Generated by Next.js',
  icons:{
    icon:"/LOGOFINAL.png"
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <body className={inter.className}>{children}</body>
    </html>
  )
}
